(define-module (guf guflayfiles)
  #:export (guflayfiles-apply)
  #:use-module (ncurses curses)
  #:use-module (guf guffile))

;;(define (my-last lst)
;;  (if (null? (cdr lst))
;;      (car lst)
;;      (my-last (cdr lst))))
;; (assoc-ref hash key)
(define (guflayfiles-list win files row)
  (when (not (null? (cdr files)))
    (addstr win (format #f "~a" (guffile-getfilename (car files)))
            #:y row #:x 0)
    (guflayfiles-list win (cdr files) (+ row 1))))

(define (guflayfiles-apply win files)
  (erase win)
  (guflayfiles-list win files 1))
