(define-module (gum gumlayfiles)
  #:export (gumlayfiles-apply)
  #:use-module (ncurses curses)
  #:use-module (gum guffile))

;;(define (my-last lst)
;;  (if (null? (cdr lst))
;;      (car lst)
;;      (my-last (cdr lst))))
;; (assoc-ref hash key)
(define (gumlayfiles-list win files row)
  (when (not (null? (cdr files)))
    (addstr win (format #f "~a" (guffile-getfilename (car files)))
            #:y row #:x 0)
    (gumlayfiles-list win (cdr files) (+ row 1))))

(define (gumlayfiles-apply win files)
  (erase win)
  (gumlayfiles-list win files 1))
